import type { LearningModule } from './types';

// Lessons 5–20 deepen the foundations. Their checks align with quiz items 5–20.
// Existing lesson IDs remain unchanged so saved completions remain valid.
type Teaching = [title: string, concept: string, example: string];
const teaching: Record<string, Teaching[]> = {
  computer: [
    ['When computers filled rooms', 'Early electronic computers used vacuum tubes to control electrical signals. These machines needed lots of space, power and cooling.', 'Draw a room-sized machine beside a pocket phone. Explain why carrying the first machine would be difficult.'],
    ['Sound becomes input', 'A microphone turns sound into signals a computer can work with. Recording begins with input, not with the speaker.', 'Pretend to record a greeting. Point to the microphone that receives your voice, then the speaker that plays it back.'],
    ['Your computer’s working desk', 'Working memory holds data that a running program needs now. It is different from storage that keeps saved files.', 'Place three number cards on a desk to add them. The desk models working memory; a folder models storage.'],
    ['Meet the instruction follower', 'The processor carries out program instructions, including calculations and comparisons. Other parts supply data or show results.', 'For 4 + 3, the keyboard supplies input, the processor calculates, and the screen displays 7. Trace those jobs.'],
    ['Pictures as output', 'Output presents the result of processing. A screen can show words, pictures, scores or messages.', 'Imagine a drawing app: moving your finger supplies input and the new line on screen is output.'],
    ['Saving along the journey', 'A program can store information during a task so it can use it again. Storage does not always happen at one fixed point.', 'A game receives your move, calculates your score, saves it and shows the result. Retell that journey.'],
    ['Listen to the output', 'Speakers turn computer signals into sound. A microphone receives sound while a speaker produces sound.', 'Name two sounds a learning app might play. Explain why hearing those sounds is output.'],
    ['Paper becomes digital', 'A scanner captures a paper page or picture as digital input. Scanning and printing move information in opposite directions.', 'Draw an arrow from a paper picture to a computer for scanning, then reverse the arrow for printing.'],
    ['Why saving matters', 'Ordinary working memory needs power. Unsaved changes held only there may disappear if power is lost.', 'You type a story but do not save it. Explain how saving regularly protects more of your work.'],
    ['Hardware you can point to', 'Hardware means physical computer parts. Screens, keyboards, circuit boards and cables are hardware.', 'Point to three hardware items without opening the device or touching any electrical connections.'],
    ['Software gives the instructions', 'Software is made of programs and instructions. The same hardware can run different software for different jobs.', 'A tablet can run a drawing app and a calculator. Name the hardware that stays the same.'],
    ['Ports connect helpers', 'Ports are connection points for compatible devices. A USB port may connect a keyboard or a storage drive.', 'With a facilitator, look at a port without inserting anything. Only connect approved devices; never force a plug.'],
    ['A processor on a chip', 'Microprocessors put processing functions on compact chips. This helped make computers smaller and more widely available.', 'Sketch a big box and a tiny chip. Discuss how smaller parts help designers build portable computers.'],
    ['A click is a message', 'Clicking sends an instruction or selection into a program. The program decides how to respond to that input.', 'Click a lesson button. Identify the input action separately from the page that appears afterward.'],
    ['From a file to a page', 'A printer produces physical output from digital information. The printed page is the result, not the input device.', 'Describe how a digital invitation could become a paper invitation, including the printer’s role.'],
    ['Instructions make the difference', 'A computer follows defined operations. To complete a task, a program needs instructions that specify what to do.', 'Give a partner exact instructions to draw a square. Compare this with telling a computer what steps to follow.'],
  ],
  algorithm: [
    ['A finish you can recognise', 'A finite algorithm completes after a limited number of steps. Its goal tells you what a successful ending looks like.', 'Write the last step for packing a school bag. How will your partner know the task is finished?'],
    ['Directions with measurements', 'Precise instructions name an action and enough detail to carry it out. Counts and directions remove guesswork.', 'Use a toy as a robot. Compare “move away” with “move forward three spaces.”'],
    ['The order changes the result', 'Sequence controls what happens first, next and last. Correct actions in the wrong order can fail.', 'Arrange these cards: open notebook, write a sentence, close notebook. Explain your order.'],
    ['A counted loop', 'A counted loop repeats a group of instructions a fixed number of times. Track the count to know when to stop.', 'Clap and tap four times. Use four counters, removing one after each clap-and-tap pair.'],
    ['State the goal first', 'A clear goal and starting situation help you choose useful steps. They also help you test the result.', 'For arranging five books by size, write the starting situation and the finished arrangement before listing steps.'],
    ['A weather decision', 'A decision chooses an action based on a condition. Different inputs can lead to different valid paths.', 'Draw two weather cards: rainy and dry. Describe what your umbrella algorithm does for each card.'],
    ['Repair the instructions', 'Debugging means finding and fixing a problem. A missing action, wrong order or unclear step can cause a bug.', 'A robot tries to write before opening its notebook. Identify the problem and rewrite the steps.'],
    ['Steps that depend on others', 'Some actions need earlier actions to be complete. These dependencies help determine the sequence.', 'Discuss making tea as a paper exercise only: water preparation comes before drinking. An adult handles hot water.'],
    ['Questions a robot can check', 'A condition is a test with a result. That result determines which instruction the algorithm follows next.', 'Use the condition “Are there fewer than five books?” Test a pile of three and a pile of seven.'],
    ['Repeat a group of steps', 'A loop can repeat several instructions together. Keep their order inside each repetition.', 'Write “step, clap” twice. Compare step-clap-step-clap with step-step-clap-clap.'],
    ['Try different starting cases', 'Testing one input is not enough to check every path. Different cases can reveal missing instructions.', 'Test a sharing algorithm with six counters, one counter and no counters. Explain what should happen each time.'],
    ['Make vague steps usable', 'An instruction should let another person act without guessing. Replace unclear words with specific actions.', 'Rewrite “put it there” using an object name and a destination, then let a partner follow it.'],
    ['Search and stop', 'A search needs an ending for both success and failure. Stop when the target is found or every candidate has been checked.', 'Search five face-down letter cards for A. Explain what to do if no card has A.'],
    ['Break a big job apart', 'Decomposition divides a large problem into smaller tasks. You can solve and test each part separately.', 'Split organising a reading corner into sorting books, arranging shelves and adding labels.'],
    ['Avoid unnecessary work', 'An efficient algorithm reaches the correct goal without needless steps. Fewer steps help only if the result stays correct.', 'Compare checking each card once with checking the same card three times during a search.'],
    ['Your everyday algorithm', 'Recipes and routines use ordered steps toward a result. They can include decisions and repeated actions.', 'Write a no-cooking snack routine on paper. Ask a partner to trace it and find any missing steps.'],
  ],
  flowchart: [
    ['A diamond becomes a choice', 'A decision in a chart can become an if/else in code. Each branch describes what happens for one result.', 'Draw “Is the bag packed?” with a yes path to leave and a no path to pack it.'],
    ['Connected steps', 'An arrow links a step to its successor. Readers should be able to follow the route without guessing.', 'Draw Start, open book and End. Add arrows and trace the route with your finger.'],
    ['Actions belong in rectangles', 'A process rectangle contains an action. Use a short verb phrase to tell the reader what happens.', 'Sketch rectangles labelled “Add the scores” and “Pack the bag.” Neither asks a question.'],
    ['Receiving information', 'Input enters a process. A parallelogram represents input or output in a standard flowchart.', 'Draw a parallelogram labelled “Enter a score.” Explain what information enters the system.'],
    ['Give every answer a route', 'A yes-or-no decision needs a route for each answer. A missing branch leaves a case unfinished.', 'Draw “Is it raining?” with only YES. Add the missing NO path and explain where it goes.'],
    ['Clear boundaries', 'Start and End make a simple finite process easier to follow. A path should lead toward its intended ending.', 'Sketch a three-action morning routine between a Start oval and an End oval.'],
    ['Threshold decisions', 'A threshold checks whether a value meets a boundary. At least 70 includes exactly 70.', 'Trace scores 69, 70 and 71 through a diamond labelled “Score at least 70?”'],
    ['Calculations are processes', 'Calculating changes input values into a result. Use a process rectangle rather than a decision diamond.', 'Put “total = 3 + 4” in a rectangle. Write the resulting value next to your chart.'],
    ['Showing a result', 'Output communicates information from the process. Showing a result belongs in an output parallelogram.', 'Draw a process that adds two numbers, then an output shape that displays the total.'],
    ['Trace one input', 'Tracing follows the path taken by a particular input. Keep track of any values that change.', 'Use score 8 in “Is score at least 5?” Follow only the matching arrow until End.'],
    ['Arrows that loop back', 'A returning arrow can repeat steps. A stopping condition lets a finite loop eventually move on.', 'Draw “Any books left?” YES leads to pack a book and return; NO leads to End.'],
    ['Labels remove guessing', 'Label decision exits with their outcomes. The label explains why someone should take that arrow.', 'Swap the YES and NO labels on a weather chart. Explain how the behaviour changes.'],
    ['A shared shape language', 'Standard symbols help different readers understand the same chart. Consistent meanings matter more than decoration.', 'Ask a partner to interpret your oval, rectangle and diamond without reading your notes.'],
    ['Find an endless route', 'A loop that never changes its condition may never finish. Trace what changes on every repetition.', 'A book-packing chart loops but never removes a book from the pile. Add the missing action.'],
    ['Paths can meet again', 'Different branches can join before a common action. You do not need to duplicate that shared step.', 'Rainy and dry paths choose different clothing, then both join at “Go to the classroom.”'],
    ['Build a complete chart', 'A simple information task can follow Start, Input, Process, Output and End. Check each connection and symbol.', 'Draw a chart that reads two scores, adds them and shows the total. Trace it with 2 and 3.'],
  ],
  code: [
    ['Repeat with a loop', 'Loops repeat instructions. A for loop can use a counter to repeat an action a planned number of times.', 'Act out a program that prints “Hello” three times. Count each repetition on your fingers.'],
    ['True without quotation marks', 'Boolean values are true and false. The text "true" is a string, which is a different kind of value.', 'Sort the cards true, false and "true" into Boolean and string groups.'],
    ['A name that stays assigned', 'const declares a binding that cannot be reassigned. Choose it when you do not intend to assign a new value.', 'Read const club = "PAL". Explain why a fixed club name is a useful example of const.'],
    ['The alternative branch', 'When an if condition is false, its else branch runs. Trace the condition before choosing the output.', 'For if (score > 5) say “High”; else say “Keep trying”, trace a score of 3.'],
    ['Calculate before displaying', 'Expressions can calculate a value before a function uses it. Numeric addition produces a numeric result.', 'Predict console.log(3 + 2), then explain why it displays 5 rather than the written calculation.'],
    ['Check what code does', 'Testing compares actual behaviour with expected behaviour. Try inputs that exercise different paths.', 'For a score >= 5 condition, write the expected outputs for scores 4, 5 and 6.'],
    ['Numbers for calculations', 'Numeric values support arithmetic. A number written without quotation marks differs from text containing digits.', 'Compare 12 and "12" on paper. Label one number and the other string.'],
    ['Text is a string', 'A string stores text, including names or messages. Quotation marks show where a text literal begins and ends.', 'Write "Ama" and "Welcome" as string examples. Use invented names, not private information.'],
    ['Set a starting value', 'A variable declaration can assign an initial value. Later instructions can read that stored value.', 'Read let score = 4. Draw a box labelled score and put a card marked 4 inside.'],
    ['Increase the score', 'Assignment can replace a value with a calculation based on its old value. score = score + 1 adds one.', 'Start with score 4 and apply the instruction twice. Write 5 and then 6 in your trace table.'],
    ['Compare with a boundary', 'The >= operator checks whether the left value is greater than or equal to the right value.', 'Evaluate age >= 9 for ages 8, 9 and 10. Mark each result true or false.'],
    ['Find a bug', 'A bug makes a program behave differently from its intended design. Debugging investigates the cause and tests a correction.', 'A score should increase but the code subtracts one. Identify the operator you would change.'],
    ['Quotes distinguish text', 'Text literals need quotation marks. Without quotes, a word may be interpreted as a variable name.', 'Compare console.log("name") with console.log(name). One prints text; the other reads a variable.'],
    ['Display a stored value', 'Passing a variable to console.log displays its value. You do not put quotes around the variable name.', 'For const name = "Esi", predict console.log(name). Then change the stored name on paper.'],
    ['Give loops a stopping rule', 'Controlled loops need a count or a condition that can end repetition. Make sure the program can reach that end.', 'Model a countdown from 3. Reduce the count after each step and stop at zero.'],
    ['Names explain your program', 'Meaningful variable names describe the data they hold. This helps other readers and your future self.', 'Compare let x = 5 with let starCount = 5. Explain which makes a star-catching game easier to understand.'],
  ],
  network: [
    ['The client asks', 'A client requests data or a service from another system. Your browser acts as a client when requesting a web page.', 'Role-play a browser asking a server for a lesson. Name the request and the expected response.'],
    ['Local connections', 'A switch links devices within a local network. It forwards data using information about connected devices.', 'Draw three computers with separate lines to a switch. Trace a message between two computers.'],
    ['A network in one place', 'LAN means Local Area Network. Its scope is a limited location such as a room, building or school.', 'Sketch a classroom LAN and label its computers and central connection device.'],
    ['Sharing without the internet', 'Local networking can work without internet access if the local devices and services still function.', 'A local server holds a worksheet. Discuss how classroom devices might reach it even if the internet connection fails.'],
    ['The centre of a star', 'A star topology connects each endpoint to a central device. Each link has its own route to the centre.', 'Arrange counters around one centre counter and draw a separate line from each to the middle.'],
    ['The server responds', 'A server provides data or services to clients. A server is a role, not necessarily a special-looking computer.', 'One learner holds lesson cards as the server while two clients request different cards.'],
    ['Devices at the edges', 'An endpoint sends or receives network data. Computers, phones and network printers can be endpoints.', 'List three possible endpoints in a learning centre and describe the information each might receive.'],
    ['Networks across distances', 'A WAN connects across a wider area than a typical LAN. It can link local networks in different places.', 'Draw two school LANs in different towns and a connection between them.'],
    ['Choosing the onward route', 'A router forwards traffic between networks. It uses routing information to choose an appropriate next destination.', 'Trace a request leaving a school LAN, passing through its router and continuing toward a website.'],
    ['Addresses and switch ports', 'A switch learns which device addresses are reachable through its ports. This helps it forward local traffic.', 'Label three switch ports A, B and C. Match a computer to each, then trace a message to computer B.'],
    ['A link made with cable', 'A wired network link can provide stable communication. Cables still need correct connections and working equipment.', 'Compare a drawn cable link with a wireless link. Never unplug classroom equipment without permission.'],
    ['Wireless access', 'Wi-Fi connects devices to a local network using radio signals. Internet access is a separate service that network may provide.', 'Draw a tablet linked wirelessly to an access point, then a separate line toward the internet.'],
    ['One broken link', 'In a star, one failed endpoint link usually affects that endpoint. Failure of the centre has a wider effect.', 'Cross out one cable in your star drawing. Identify which devices can still use their own links.'],
    ['Names become addresses', 'DNS helps translate a domain name into the network address needed to contact a service.', 'Use a pretend directory to look up pal-tech.vercel.app. Explain why people prefer names over memorising addresses.'],
    ['Messages in pieces', 'Network data commonly travels in packets. These pieces carry information that helps deliver and reconstruct a message.', 'Split a sentence across numbered paper cards. Reorder the cards to reconstruct the sentence.'],
    ['Agreed communication rules', 'Protocols define rules for formatting and exchanging data. Shared rules help different devices communicate.', 'Agree that every paper message starts with a receiver name and ends with END. Try sending one without those rules.'],
  ],
  ai: [
    ['Check an important claim', 'AI output can contain errors. Important factual claims need checking against reliable evidence outside the generated answer.', 'An AI names a book you cannot find. Describe how a library catalogue could help check whether it exists.'],
    ['An estimate, not a promise', 'A prediction is an estimated answer based on learned patterns. New evidence may show the estimate is wrong.', 'A fruit classifier guesses “mango” for a blurry picture. Explain why a guess needs checking.'],
    ['Who is missing from the data?', 'If training examples leave out groups or conditions, performance may be uneven. Check who the examples represent.', 'A handwriting model sees only one person’s writing. Discuss what might happen with a different writing style.'],
    ['A fair test uses new examples', 'Separate test examples help reveal whether a model learned useful patterns beyond the examples it saw during training.', 'Teach a partner using six picture cards, then test with two different cards kept aside.'],
    ['Confident words can be wrong', 'Confident wording does not prove accuracy. A prediction score is also not a guarantee of correctness.', 'Compare a loudly spoken wrong answer with a carefully checked answer. Which has better evidence?'],
    ['Permission before pictures', 'Photos can reveal personal information. AI activities should use approved material and respect permission and privacy.', 'For a pretend image activity, use drawings of fruit instead of uploading classmates’ faces.'],
    ['Examples teach patterns', 'Training uses examples to adjust a model. Relevant examples help connect features with useful outputs.', 'Sort drawings of ripe and unripe fruit. Explain which visible features might help distinguish the groups.'],
    ['What a model does', 'An AI model applies patterns learned from data to produce outputs. It is not a person hidden inside a machine.', 'Draw input picture, model and predicted label. Explain the job of each part.'],
    ['New situations can be tricky', 'A model may fail when new inputs differ from its training examples. Check performance under varied conditions.', 'A model trained on bright photos receives a dark photo. Explain why this could be harder.'],
    ['Spot uneven results', 'Bias can create unfair differences in outcomes. Data, design and use all deserve careful review.', 'A pretend recogniser works on printed writing but fails on cursive. Discuss who may be left out and what to test.'],
    ['People remain responsible', 'People should review important decisions, especially decisions affecting other people. AI should not remove accountability.', 'A tool suggests who needs extra learning help. Explain why a qualified teacher must review that suggestion.'],
    ['Look for independent evidence', 'Repeating an AI claim does not verify it. Independent reliable sources provide a separate basis for checking.', 'An AI gives a historical date. Compare a trusted reference book with a second reliable source.'],
    ['Keep private data out', 'Do not enter private personal information into public AI tools. Use fictional examples and follow the facilitator’s approved process.', 'Replace a real address in a practice prompt with “a fictional town.” Explain what you protected.'],
    ['Say how you used AI', 'Transparency means explaining where AI helped and what you checked or changed. You remain responsible for the work.', 'Write a project note: “AI suggested titles. I chose one and wrote the story myself.”'],
    ['Human review can change results', 'Human oversight means a person can examine, question and correct an AI-supported result rather than accept it automatically.', 'A tool labels a pineapple as a mango. Describe what a reviewer should do before publishing the label.'],
    ['Plan a fruit dataset', 'Useful training examples match the task and include relevant variety. Labels should describe the examples accurately.', 'Plan a collection of mango, orange and pineapple drawings with different sizes and views. Reserve some for testing.'],
  ],
  safety: [
    ['Your online trail', 'Online actions can leave records. Posts may be copied, so removing the original does not guarantee every copy disappears.', 'Discuss a fictional photo copied into another chat. Who might still have it after the first post is deleted?'],
    ['Pressure is a warning sign', 'Messages that demand passwords or rush you with prizes deserve caution. Pause instead of reacting to urgency.', 'Inspect a pretend message: “Send your password now to win.” Name two warning signs without opening any link.'],
    ['You can ask for help', 'If an online interaction makes you uncomfortable, tell a trusted adult. You do not need to handle it alone.', 'Name a trusted adult you could speak to. Practise saying, “This message worries me. Can you help?”'],
    ['Different accounts, different passwords', 'Reusing a password lets one leak endanger other accounts. Unique passwords limit that risk.', 'Use pretend keys and boxes to explain why one key for every box creates a bigger problem if lost.'],
    ['A nickname is enough', 'Share only the information an activity needs. A learning nickname can help identify your progress without exposing private details.', 'Invent a safe nickname for a fictional learner. Leave out their full name, address and school location.'],
    ['An unexpected prize', 'Unknown prize links can trick people into giving information or downloading harmful files. Ask a trusted adult before acting.', 'Role-play receiving a prize message from someone you do not know. Practise a safe response without clicking.'],
    ['Impersonation tricks', 'Phishing pretends to be trustworthy to obtain information or actions. A familiar logo alone does not prove a message is genuine.', 'A pretend message claims to be your school but asks for a password. Explain how to check with the school separately.'],
    ['Long and memorable', 'A long, unique passphrase can be easier to remember and harder to guess than a short common password.', 'Discuss passphrase principles with made-up words only. Never write a real password into a lesson or shared document.'],
    ['Another proof of identity', 'Multi-factor authentication adds another kind of proof alongside a password. Keep verification codes private too.', 'A pretend sign-in asks for a password and a code. Explain why you should not send the code to a stranger.'],
    ['A mistake needs support', 'If a password is shared by accident, tell a trusted adult promptly and get help securing the account.', 'Practise explaining the mistake calmly. Asking for help quickly is useful; hiding it can delay protection.'],
    ['Background clues reveal places', 'Photos may reveal location through signs, uniforms or landmarks. Check the whole image before sharing.', 'Draw a fictional photo with a street sign in the background. Circle the detail that could reveal location.'],
    ['Respond to hurtful messages', 'Repeated hurtful messages deserve support. A trusted adult can help preserve appropriate evidence and use blocking or reporting tools.', 'Discuss a fictional mean message. Practise asking for help rather than retaliating or meeting the sender.'],
    ['Updates can repair weaknesses', 'Trusted security updates can fix known weaknesses. Ask the device owner or facilitator to manage updates appropriately.', 'Explain why an official update differs from an unexpected pop-up telling you to disable protection.'],
    ['Choose trusted downloads', 'Downloads can contain harmful software. Use approved sources and ask before installing anything on a shared device.', 'Compare a facilitator-approved app with an unknown prize attachment. Explain which source is more trustworthy.'],
    ['Permission should be clear', 'Consent means clear permission with an understanding of how something will be used. Silence does not automatically mean agreement.', 'Practise asking whether a fictional project photo may be shared and accepting “no” respectfully.'],
    ['Your safety routine', 'Stop, Think, Check and Ask creates time to recognise uncertainty and seek support before taking action.', 'Apply the four steps to a pretend message asking for your home address. Explain what you would do at each step.'],
  ],
  skills: [
    ['Names that help you find work', 'A descriptive filename explains what a file contains. Keep private information out of names intended for sharing.', 'Compare “Document1” with “PAL-Reading-Reflection.” Choose which will be easier to recognise next week.'],
    ['Find an average', 'AVERAGE calculates the arithmetic mean of numeric values. It adds the numbers and divides by how many numbers there are.', 'For values 2, 4, 6 and 8 in B2:B5, predict =AVERAGE(B2:B5). The mean is 5.'],
    ['A heading that stands out', 'A clear heading helps readers recognise the topic. Size, spacing and readable contrast establish importance.', 'Write a title above a short paragraph. Make the title easier to spot without making the paragraph hard to read.'],
    ['A consistent slide style', 'Repeated fonts and colours help slides feel related. Consistency makes it easier to focus on the message.', 'Plan three slides using one title style and one body style rather than changing every font.'],
    ['Save as you go', 'Saving regularly protects changes. Check where the file is saved and whether the latest version is present.', 'After writing a paragraph, save it and confirm its filename and folder with your facilitator.'],
    ['Compare with bars', 'Bar and column charts compare values across categories. Clear labels tell readers what each bar represents.', 'Sketch bars for fictional scores 4, 6 and 8. Label the topics and use an evenly spaced scale.'],
    ['Lists organise ideas', 'Bullets group related points. Numbering is useful when order matters, such as a sequence of instructions.', 'Turn a list of materials into bullets and a short procedure into numbered steps. Explain the difference.'],
    ['A cell has an address', 'Spreadsheet references combine the column letter and row number. B3 is at column B and row 3.', 'Draw a small grid with columns A to C and rows 1 to 4. Mark B3.'],
    ['Add a range of cells', 'SUM adds numbers in a range. A colon connects the first and last cells and includes the cells between them.', 'Put 1, 2, 3, 4 and 5 in A1:A5 on paper. Predict =SUM(A1:A5), which gives 15.'],
    ['Give a chart context', 'A chart title explains what the values describe. Labels and units help readers interpret the comparison.', 'Improve the title “Chart” to “Books read this month.” Add category labels to a sketch.'],
    ['One idea per slide', 'A focused slide supports one main idea. Extra details can go into what the presenter says rather than tiny text.', 'Plan one slide explaining input devices. Select one relevant picture and a short explanation.'],
    ['Recognise a presentation file', 'The .pptx extension commonly identifies a PowerPoint presentation. Recognising extensions helps you choose the correct file.', 'Sort pretend filenames lesson.pptx, scores.xlsx and notes.docx by the kind of work they contain.'],
    ['Recognise a workbook', 'An .xlsx file is commonly an Excel workbook. It can hold worksheets with cells, formulas and charts.', 'Choose a filename for a fictional reading-count workbook and explain why .xlsx fits it.'],
    ['Review before handing in', 'Proofreading checks meaning, spelling and missing information. Confirm the correct version is saved before submitting.', 'Review a short paragraph with an intentional typo. Correct it, then check the title and saved filename.'],
    ['A folder for your project', 'Folders group related files so they are easier to find. A clear organisation system helps avoid duplicate or lost versions.', 'Sketch a PAL Project folder containing a document, a workbook and a presentation.'],
    ['Pictures that explain', 'A useful visual supports the slide’s idea and remains readable. Use images you have permission to use.', 'For a slide about keyboards, choose a clear keyboard picture over an unrelated landscape. Explain your choice.'],
  ],
};

export function expandLessons(module: LearningModule): LearningModule {
  const additions = teaching[module.id];
  if (!additions || additions.length !== 16) throw new Error(`Missing lesson content for ${module.id}`);
  return { ...module, lessons: [...module.lessons, ...additions.map(([title, concept, example], index) => {
    const question = module.questions[index + 4];
    // Rotate choices so the correct answer is not always first.
    const offset = index % question.choices.length;
    return { id: `${module.id}-extended-${index + 5}`, title, eyebrow: index < 6 ? 'Explore' : index < 12 ? 'Practise' : 'Apply', concept, example,
      challenge: question.prompt, choices: [...question.choices.slice(offset), ...question.choices.slice(0, offset)], answer: question.answer, explanation: question.explanation };
  })] };
}
